#!/usr/bin/env python
import codecs
import re
import cchardet
import os
import argparse
import traceback
from termcolor import colored, cprint

parser = argparse.ArgumentParser()
parser.add_argument("-l", "--language", help="choose language to convert", default="kr")
parser.add_argument("dir", help="target directory. ex) ./smi2srt -t ./Movies", default="./")

args = parser.parse_args()

PATH = args.dir
LANG = args.language.upper()+"CC"

def output_postfix(lang):
    if LANG == 'KRCC':
        return ".ko"
    elif LANG == "ENCC":
        return ".en"
    return ""

def parse(smi): # smi parsing algorithm written in PYSAMI by g6123 (https://github.com/g6123/PySAMI)
    search = lambda string, pattern: re.search(pattern, string, flags=re.I)

    def split_content(string, tag):
        threshold = '<'+tag

        return list(map(
            lambda item: (threshold+item).strip(),
            re.split(threshold, string, flags=re.I)
        ))[1:]

    def parse_p(item):
        lang = search(item, '<p(.+)class=([a-z]+)').group(2)
        content = item[search(item, '<p[^>]+>').end():]
        content = content.replace('\r', '')
        content = content.replace('\n', '')
        content = re.sub('<br ?/?>', '\n', content, flags=re.I)
        content = re.sub('<[^>]+>','', content)
        content = content.strip()
        return [lang, content]

    data = []

    try:
        for item in split_content(smi, 'sync'):
            pattern = search(item, '<sync start=([0-9]+)')
            if pattern!=None:
                timecode = pattern.group(1)
                content = dict(map(parse_p, split_content(item, 'p')))
                data.append([timecode, content])
    except:
        cprint("Conversion ERROR: maybe this file is not supported.", "red", attrs=['bold'])
        cprint(traceback.format_exc(), "magenta")
    return data

def convert(data, lang): # written by ncianeo
    if lang not in data[0][1].keys():
        print("lang: %s is not found. will use the first lang in the smi file." %lang)
        i=0
        while True:
            try:
                lang = list(data[i][1].keys())[0]
                break
            except:
                i+=1
        print("chosen lang: %s" %lang)
    def ms_to_ts(time):
        time = int(time)
        ms = time%1000
        s = int(time/1000)%60
        m = int(time/1000/60)%60
        h = int(time/1000/60/60)
        return (h,m,s,ms)
    srt=''
    sub_nb = 1
    for i in range(len(data)-1):
        try:
            if i>0:
                if data[i][0]<data[i-1][0]:
                    continue
            if data[i][1][lang]!='&nbsp;':
                srt+=str(sub_nb)+'\n'
                sub_nb+=1
                if data[i+1][0]>data[i][0]:
                    srt+='%02d:%02d:%02d,%03d' %ms_to_ts(data[i][0])+' --> '+'%02d:%02d:%02d,%03d\n' %ms_to_ts(data[i+1][0])
                else:
                    srt+='%02d:%02d:%02d,%03d' %ms_to_ts(data[i][0])+' --> '+'%02d:%02d:%02d,%03d\n' %ms_to_ts(int(data[i][0])+1000)
                srt+=data[i][1][lang]+'\n\n'
        except:
            continue
    return srt

cprint("media library path: "+PATH, 'white', attrs=['bold'])
success=[]
fail=[]
cprint("finding and converting started...", 'white', attrs=['bold'])
for p,w,f in os.walk(PATH):
    for file_name in f:
        if file_name[-4:].lower()=='.smi':
            print('processing %s' %os.path.join(p,file_name))
            try:
                with open(os.path.join(p,file_name),'rb') as smi_file:
                    smi_raw = smi_file.read()
                    encoding = cchardet.detect(smi_raw)
                smi = smi_raw.decode(encoding['encoding'])
                srt_file = codecs.open(os.path.join(p,os.path.splitext(file_name)[0]+output_postfix(LANG)+'.srt'),'w',encoding='utf-8')
                srt_file.write(convert(parse(smi),LANG))
                success.append({'name': file_name})
            except:
                fail.append({'name': file_name, 'error': traceback.format_exc()})

smi_list = list(set(map(lambda x: x['name'], success)) | set(map(lambda x: x['name'], fail)))
cprint('\nfound .smi subtitles:', 'white', attrs=['bold'])
for smi_name in smi_list:
    cprint(smi_name, 'white')

cprint('\nworked .smi subtitles:', 'green', attrs=['bold'])
for smi in success:
    cprint(smi['name'],'green')

cprint('\nfailed .smi subtitles:', 'red', attrs=['bold'])
for smi in fail:
    cprint(smi['name'], 'red')
    cprint(smi['error'], 'magenta')
